CREATE TABLE MAIN_ACCOM (
    ACCOM_CODE VARCHAR2(50) PRIMARY KEY
    , ACCOM_NAME VARCHAR2(50) NOT NULL
    , ACCOM_ADDR VARCHAR2(100)
    , ACCOM_INTRO VARCHAR2(100)
    , ACCOM_CATE VARCHAR2(50)
);

CREATE TABLE MAIN_ACCOM_IMG (
    MAIN_IMG_CODE VARCHAR2(20) PRIMARY KEY
    , ORIGIN_FILE_NAME VARCHAR2(100)
    , ATTACHED_FILE_NAME VARCHAR2(100)
    , ACCOM_CODE VARCHAR2(50) NOT NULL, FOREIGN KEY (ACCOM_CODE) REFERENCES MAIN_ACCOM(ACCOM_CODE)
    , IS_MAIN VARCHAR2(3)
);

CREATE TABLE SUB_ACCOM (
    SUB_ACCOM_CODE VARCHAR2(50) PRIMARY KEY
    , ACCOM_CODE VARCHAR2(50) NOT NULL, FOREIGN KEY (ACCOM_CODE) REFERENCES MAIN_ACCOM(ACCOM_CODE)
    , SUB_ACCOM_NAME VARCHAR2(50)
    , SUB_ACCOM_INTRO VARCHAR2(100)
    , SUB_ACCOM_CATE VARCHAR2(50)
    , ACCOM_PRICE VARCHAR2(20)
    , BASIC_MAN NUMBER
    , MAX_MAN NUMBER
    , ACCOM_START_TIME VARCHAR2(30)
    , ACCOM_END_TIME VARCHAR2(30)
    , RENT_TIME VARCHAR2(30)
);

CREATE TABLE SUB_ACCOM_IMG (
    SUB_IMG_CODE VARCHAR2(20) PRIMARY KEY
    , ORIGIN_FILE_NAME VARCHAR2(100)
    , ATTACHED_FILE_NAME VARCHAR2(100)
    , SUB_ACCOM_CODE VARCHAR2(50) NOT NULL, FOREIGN KEY (SUB_ACCOM_CODE) REFERENCES SUB_ACCOM(SUB_ACCOM_CODE)
    , IS_MAIN VARCHAR2(3)
);

CREATE TABLE ACCOM_REVIEW (
    ACCOM_CODE VARCHAR2(50) NOT NULL, FOREIGN KEY (ACCOM_CODE) REFERENCES MAIN_ACCOM(ACCOM_CODE)
    , REVIEW_POINT NUMBER
    , REVIEW_DETAIL VARCHAR2(100)
    , ORIGIN_FILE_NAME VARCHAR2(100)
    , ATTACHED_FILE_NAME VARCHAR2(100)
    , REVIEW_DATE VARCHAR2(30)
);

ALTER TABLE SUB_ACCOM ADD SOLD_OUT VARCHAR2(3) DEFAULT 'N';