DROP TABLE MAIN_ACCOM;

CREATE TABLE MAIN_ACCOM (
    ACCOM_CODE VARCHAR2(50) PRIMARY KEY
    , ACCOM_NAME VARCHAR2(50) NOT NULL
    , ACCOM_ADDR VARCHAR2(100)
    , ACCOM_INTRO VARCHAR2(100)
    , ACCOM_CATE VARCHAR2(50)
);

CREATE TABLE MAIN_ACCOM_IMG (
    MAIN_IMG_CODE VARCHAR2(20) PRIMARY KEY
    , ORIGIN_FILE_NAME VARCHAR2(100)
    , ATTACHED_FILE_NAME VARCHAR2(100)
    , ACCOM_CODE VARCHAR2(50) NOT NULL, FOREIGN KEY (ACCOM_CODE) REFERENCES MAIN_ACCOM(ACCOM_CODE)
    , IS_MAIN VARCHAR2(3)
);

CREATE TABLE SUB_ACCOM (
    SUB_ACCOM_CODE VARCHAR2(50) PRIMARY KEY
    , ACCOM_CODE VARCHAR2(50) NOT NULL, FOREIGN KEY (ACCOM_CODE) REFERENCES MAIN_ACCOM(ACCOM_CODE)
    , SUB_ACCOM_NAME VARCHAR2(50)
    , SUB_ACCOM_INTRO VARCHAR2(100)
    , SUB_ACCOM_CATE VARCHAR2(50)
    , ACCOM_PRICE VARCHAR2(20)
    , BASIC_MAN NUMBER
    , MAX_MAN NUMBER
    , ACCOM_START_TIME VARCHAR2(30)
    , ACCOM_END_TIME VARCHAR2(30)
    , RENT_TIME VARCHAR2(30)
);

CREATE TABLE SUB_ACCOM_IMG (
    SUB_IMG_CODE VARCHAR2(20) PRIMARY KEY
    , ORIGIN_FILE_NAME VARCHAR2(100)
    , ATTACHED_FILE_NAME VARCHAR2(100)
    , SUB_ACCOM_CODE VARCHAR2(50) NOT NULL, FOREIGN KEY (SUB_ACCOM_CODE) REFERENCES SUB_ACCOM(SUB_ACCOM_CODE)
    , IS_MAIN VARCHAR2(3)
);

CREATE TABLE ACCOM_REVIEW (
    ACCOM_CODE VARCHAR2(50) NOT NULL, FOREIGN KEY (ACCOM_CODE) REFERENCES MAIN_ACCOM(ACCOM_CODE)
    , REVIEW_POINT NUMBER
    , REVIEW_DETAIL VARCHAR2(100)
    , ORIGIN_FILE_NAME VARCHAR2(100)
    , ATTACHED_FILE_NAME VARCHAR2(100)
    , REVIEW_DATE VARCHAR2(30)
);


ALTER TABLE SUB_ACCOM ADD SOLD_OUT VARCHAR2(3) DEFAULT 'N';

ALTER TABLE MAIN_ACCOM ADD ACCOM_CEO VARCHAR2(50) REFERENCES JEJU_MEMBER(MEMBER_ID);



CREATE TABLE ACCOM_CATEGORY(
    ACCOM_CATE VARCHAR2(50) PRIMARY KEY
    , CATE_NAME VARCHAR2(30) -- 00. 제주시, 01.서귀포 02.조천읍 03.구좌읍 04.성산읍 05.표선면 06.남원읍 07.안덕면 08.대정읍 09.한경면 10.한림읍 11.애월읍
);

INSERT INTO ACCOM_CATEGORY (ACCOM_CATE, CATE_NAME) VALUES ('CATE_001', '호텔');
INSERT INTO ACCOM_CATEGORY (ACCOM_CATE, CATE_NAME) VALUES ('CATE_002', '모텔');
INSERT INTO ACCOM_CATEGORY (ACCOM_CATE, CATE_NAME) VALUES ('CATE_003', '펜션');
INSERT INTO ACCOM_CATEGORY (ACCOM_CATE, CATE_NAME) VALUES ('CATE_004', '글램핑');

CREATE TABLE ACCOM_LOC(
    ACCOM_LOC_CODE VARCHAR2(50) PRIMARY KEY
    , LOC_NAME VARCHAR2(30) -- 00. 제주시, 01.서귀포 02.조천읍 03.구좌읍 04.성산읍 05.표선면 06.남원읍 07.안덕면 08.대정읍 09.한경면 10.한림읍 11.애월읍
);
DROP TABLE ACCOM_LOC;

INSERT INTO ACCOM_LOC (ACCOM_LOC_CODE, LOC_NAME) VALUES ('00', '제주시');
INSERT INTO ACCOM_LOC (ACCOM_LOC_CODE, LOC_NAME) VALUES ('01', '서귀포시');
INSERT INTO ACCOM_LOC (ACCOM_LOC_CODE, LOC_NAME) VALUES ('02', '조천읍');
INSERT INTO ACCOM_LOC (ACCOM_LOC_CODE, LOC_NAME) VALUES ('03', '구좌읍');
INSERT INTO ACCOM_LOC (ACCOM_LOC_CODE, LOC_NAME) VALUES ('04', '성산읍');
INSERT INTO ACCOM_LOC (ACCOM_LOC_CODE, LOC_NAME) VALUES ('05', '표선면');
INSERT INTO ACCOM_LOC (ACCOM_LOC_CODE, LOC_NAME) VALUES ('06', '남원읍');
INSERT INTO ACCOM_LOC (ACCOM_LOC_CODE, LOC_NAME) VALUES ('07', '안덕면');
INSERT INTO ACCOM_LOC (ACCOM_LOC_CODE, LOC_NAME) VALUES ('08', '대정읍');
INSERT INTO ACCOM_LOC (ACCOM_LOC_CODE, LOC_NAME) VALUES ('09', '한경면');
INSERT INTO ACCOM_LOC (ACCOM_LOC_CODE, LOC_NAME) VALUES ('10', '한립음');
INSERT INTO ACCOM_LOC (ACCOM_LOC_CODE, LOC_NAME) VALUES ('11', '애월읍');


ALTER TABLE MAIN_ACCOM ADD ACCOM_LOC_CODE VARCHAR2(30) REFERENCES ACCOM_LOC(ACCOM_LOC_CODE);
ALTER TABLE MAIN_ACCOM DROP COLUMN ACCOM_CATE;
ALTER TABLE MAIN_ACCOM DROP COLUMN ACCOM_LOC_CODE;
ALTER TABLE MAIN_ACCOM ADD ACCOM_CATE VARCHAR2(30) REFERENCES ACCOM_CATEGORY(ACCOM_CATE);
ALTER TABLE MAIN_ACCOM ADD LATITUDE VARCHAR2(30);
ALTER TABLE MAIN_ACCOM ADD LONGITUDE VARCHAR2(30);

