--예약
CREATE TABLE RESERVATION_STAY_ACCOM(
 RESERVATION_CODE  VARCHAR2(30) PRIMARY KEY --RES_001, RES_002
 , SUB_ACCOM_CODE VARCHAR2(30) REFERENCES SUB_ACCOM(SUB_ACCOM_CODE)--수정해야 함
 , MEMBER_ID VARCHAR2(50) REFERENCES JEJU_MEMBER(MEMBER_ID)--수정해야 함
 , STAY_START_DATE VARCHAR2(20)
 , STAY_END_DATE VARCHAR2(20)
 , RESERVATION_DATE DATE DEFAULT SYSDATE
 , RESERVATION_NAME VARCHAR2(40)
 , RESERVATION_PRICE NUMBER
 , DAY_USE VARCHAR2(10)
);
--구매전 장바구니
CREATE TABLE BASKET_STAY_ACCOM (
    BASKET_CODE VARCHAR2(30) PRIMARY KEY  --BAS_001, BAS_002
    , SUB_ACCOM_CODE VARCHAR2(30) REFERENCES SUB_ACCOM(SUB_ACCOM_CODE)--수정해야 함
    , MEMBER_ID VARCHAR2(50) REFERENCES JEJU_MEMBER(MEMBER_ID)--수정해야 함
    , STAY_START_DATE VARCHAR2(20)
    , STAY_END_DATE VARCHAR2(20)
    , STAY_TERM NUMBER
    , DAY_USE VARCHAR2(10) DEFAULT 'N'
);
--예약 상태 리뷰작성 유무 환불 유무
CREATE TABLE RESERVATION_STATE(
RESERVATION_STATE_CODE VARCHAR2(30) PRIMARY KEY  --RES_001, RES_002
 , RESERVATION_CODE VARCHAR2(30) REFERENCES RESERVATION_STAY_ACCOM(RESERVATION_CODE)
 , REFUND VARCHAR2(10) DEFAULT 'N'
 , REVIEW VARCHAR2(10) DEFAULT 'N'
 , REFUND_PRICE NUMBER DEFAULT 0
 , REFUND_DATE DATE DEFAULT NULL --환불한 날자
 , CAN_REFUND_DATE DATE --환불 가능 날짜
 , OVER_DATE DATE --숙박 종료 날짜
);
--리뷰 
CREATE TABLE REVIEW (
    REVIEW_CODE VARCHAR2(30) PRIMARY KEY  --REV_001, REV_002
    , ACCOM_CODE VARCHAR2(30) REFERENCES MAIN_ACCOM(ACCOM_CODE)
    , MEMBER_ID VARCHAR2(50) REFERENCES JEJU_MEMBER(MEMBER_ID)
    , RESERVATION_CODE VARCHAR2(30) REFERENCES RESERVATION_STAY_ACCOM(RESERVATION_CODE) UNIQUE
    , SCORE NUMBER
    , CONTENT VARCHAR2(500)
    , WRITE_DATE DATE DEFAULT SYSDATE
);

--리뷰 이미지
CREATE TABLE REVIEW_IMG(
    REVIEW_IMG_CODE VARCHAR2(50) CONSTRAINT PK_IMG PRIMARY KEY --RIMG_001,RIMG_002
    , ORIGIN_FILE_NAME VARCHAR2(100) NOT NULL --원본파일명
    , ATTACHED_FILE_NAME VARCHAR2(100) NOT NULL --첨부된 파일명
    , REVIEW_CODE VARCHAR2(50) CONSTRAINT FK_IMG
      REFERENCES REVIEW (REVIEW_CODE) 
);
--리뷰 답변
CREATE TABLE REVIEW_ADMIN (
    REVIEW_ADMIN_CODE VARCHAR2(30) PRIMARY KEY  --READ_001, READ_002
    , ADMIN_MEMBER_ID VARCHAR2(50) REFERENCES JEJU_MEMBER(MEMBER_ID)
    , REVIEW_CODE VARCHAR2(30) REFERENCES REVIEW(REVIEW_CODE)--수정해야 함
    , ADMIN_CONTENT VARCHAR2(500)
    , ADMIN_WRITE_DATE DATE DEFAULT SYSDATE
);
--플래너 정보
CREATE TABLE STAY_PLAN(
 STAY_PLAN_CODE  VARCHAR2(30) PRIMARY KEY --RESERVATION_CODE + DAY_(day)
 , RESERVATION_CODE VARCHAR2(30) REFERENCES RESERVATION_STAY_ACCOM(RESERVATION_CODE)
 , PLAN_DATE DATE
 , BREAKFAST_NAME VARCHAR2(30)
 , BREAKFAST_ADDR VARCHAR2(50)
 , BREAKFAST_TIME VARCHAR2(30)
 , LUNCH_NAME VARCHAR2(30)
 , LUNCH_ADDR VARCHAR2(50)
 , LUNCH_TIME VARCHAR2(30)
 , DINNER_NAME VARCHAR2(30)
 , DINNER_ADDR VARCHAR2(50)
 , DINNER_TIME VARCHAR2(30)
 , POINT_ONE_NAME VARCHAR2(30)
 , POINT_ONE_ADDR VARCHAR2(50)
 , POINT_ONE_TIME VARCHAR2(30)
 , POINT_TWO_NAME VARCHAR2(30)
 , POINT_TWO_ADDR VARCHAR2(50)
 , POINT_TWO_TIME VARCHAR2(30)
);


