// 회원 등록 테이블
CREATE TABLE JEJU_MEMBER(
    MEMBER_ID VARCHAR2(50) CONSTRAINT PK_MEMBER PRIMARY KEY
    , MEMBER_PW VARCHAR2(50) NOT NULL
    , MEMBER_NAME VARCHAR2(50) NOT NULL
    , MEMBER_TEL VARCHAR2(30) UNIQUE -- 010-1111-2222
    , GENDER VARCHAR2(5) ---- '남','여'
    , BIRTH_DATE VARCHAR2(20)
    , MEMBER_MAIL VARCHAR(30) NOT NULL
    , MEMBER_ROLL VARCHAR2(7) DEFAULT 'USER' -- USER, ADMIN, MANAGER

);

-- 회원등록 (관리자)
INSERT INTO JEJU_MEMBER(
    MEMBER_ID
    , MEMBER_PW
    , MEMBER_NAME
    , MEMBER_TEL
    , GENDER
    , BIRTH_DATE
    , MEMBER_MAIL
)VALUES(
    'admin'
    , '1111'
    , '관리자'
    , '010-1111-1111'
    , '남'
    , '1996-01-01'
    , 'admin@naver.com'
);

// admin에 관리자 권한 부여
UPDATE JEJU_MEMBER
SET MEMBER_ROLL = 'ADMIN'
WHERE MEMBER_ID = 'admin';

// 공지사항 테이블
CREATE TABLE ANNOUNCEMENT(
    ANN_NUM NUMBER CONSTRAINT PK_ANN PRIMARY KEY
    , ANN_CATE VARCHAR2(50) NOT NULL
    , ANN_WRITER VARCHAR2(50) CONSTRAINT FK_ANN_MEMBER_ID
    REFERENCES JEJU_MEMBER (MEMBER_ID)
    , ANN_TITLE VARCHAR2(100) NOT NULL
    , ANN_CONTENT VARCHAR2(1000) NOT NULL  --썸머노트
    , ANN_DATE DATE DEFAULT SYSDATE
);

DROP TABLE ANNOUNCEMENT;

SELECT * FROM JEJU_MEMBER;
SELECT * FROM ANNOUNCEMENT;

INSERT INTO ANNOUNCEMENT (
    ANN_NUM
    , ANN_CATE
    , ANN_WRITER
    , ANN_TITLE
    , ANN_CONTENT
    )
VALUES(
    (SELECT NVL(MAX(ANN_NUM), 0) + 1
    FROM ANNOUNCEMENT)
    , 'CATE_001'
    , 'admin'
    , '제목'
    , '내용'
);