--기본키
--작성자(외래키)
--숙박시설명(객실명+)(외래키)
--점수(2~10)별5개로 표현
--내용
--사진 
--sysdate

--숙소답변

--기본키(리뷰)
--외래키
--내용
--sysdate

DROP TABLE REVEIW;

CREATE TABLE REVEIW (
    REVEIW_CODE VARCHAR2(30) PRIMARY KEY  --REV_001, REV_002
    , ACCOM_CODE VARCHAR2(30) REFERENCES MAIN_ACCOM(ACCOM_CODE)--수정해야 함
    , MEMBER_ID VARCHAR2(50) REFERENCES JEJU_MEMBER(MEMBER_ID)--수정해야 함
    , SCORE NUMBER
    , CONTENT VARCHAR2(500)
    --사진
    , WRITE_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE REVEIW_ADMIN (
    BASKET_CODE VARCHAR2(30) PRIMARY KEY  --BAS_001, BAS_002
    , SUB_ACCOM_CODE VARCHAR2(30) REFERENCES SU_ACCOM(SUB_ACCOM_CODE)--수정해야 함
    , STAY_TERM VARCHAR2(10)
    , WRITE_DATE DATE DEFAULT SYSDATE
);




